"use client";

import Link from "next/link";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function AdminPage() {
  return (
      <>
            <Navbar />

                  <main className="min-h-screen bg-[#040816] text-white">

                          <section className="max-w-7xl mx-auto px-6 py-20">

                                    <h1 className="text-5xl font-black mb-10">
                                                Tableau de bord
                                                          </h1>

                                                                    <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">

                                                                                <Link
                                                                                              href="/admin/produits"
                                                                                                            className="rounded-3xl border border-cyan-900 bg-[#08111f] p-8 hover:border-cyan-400 transition"
                                                                                                                        >
                                                                                                                                      <h2 className="text-2xl font-bold">
                                                                                                                                                      📦 Produits
                                                                                                                                                                    </h2>

                                                                                                                                                                                  <p className="mt-4 text-gray-400">
                                                                                                                                                                                                  Gérer les produits
                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                      href="/admin/commandes"
                                                                                                                                                                                                                                                                    className="rounded-3xl border border-cyan-900 bg-[#08111f] p-8 hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                              📋 Commandes
                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                          <p className="mt-4 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                          Voir les commandes
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                    </Link>

                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                              href="/admin/utilisateurs"
                                                                                                                                                                                                                                                                                                                                                                                                                            className="rounded-3xl border border-cyan-900 bg-[#08111f] p-8 hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      👥 Utilisateurs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-4 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Comptes clients
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/admin/statistiques"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-3xl border border-cyan-900 bg-[#08111f] p-8 hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              📊 Statistiques
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-4 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Chiffres de la boutique
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }