export default function AboutSection() {
          return (
              <section className="py-24 px-6">

                    <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-20 items-center">

                            <div>

                                      <img
                                                  src="/image/logo.png"
                                                              alt="AONAMI"
                                                                          className="w-full max-w-md mx-auto drop-shadow-[0_0_60px_rgba(34,211,238,.5)]"
                                                                                    />

                                                                                            </div>

                                                                                                    <div>

                                                                                                              <p className="uppercase tracking-[5px] text-cyan-400">
                                                                                                                          Notre univers
                                                                                                                                    </p>

                                                                                                                                              <h2 className="text-5xl font-black mt-4">
                                                                                                                                                     Découvrez l'univers passionnant
                                                                                                                                                                d'AONAMITCG
                                                                                                                                                                      
                                                                                                                                                                                </h2>

                                                                                                                                                                                          <p className="mt-8 text-gray-400 leading-9 text-lg">

                                                                                                                                                                                                      Chez AONAMI TCG nous sélectionnons uniquement
                                                                                                                                                                                                                  des produits officiels.

                                                                                                                                                                                                                              Notre objectif est de proposer la meilleure
                                                                                                                                                                                                                                          expérience possible aux collectionneurs et
                                                                                                                                                                                                                                                      aux joueurs.

                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 gap-6 mt-12">

                                                                                                                                                                                                                                                                                      <div className="rounded-2xl bg-[#091223] border border-cyan-900 p-6">

                                                                                                                                                                                                                                                                                                    <h3 className="text-4xl font-black text-cyan-400">
                                                                                                                                                                                                                                                                                                                    500+
                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                Produits disponibles
                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-2xl bg-[#091223] border border-cyan-900 p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-4xl font-black text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                    1200+
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Clients satisfaits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-2xl bg-[#091223] border border-cyan-900 p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-4xl font-black text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    24h
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Expédition
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="rounded-2xl bg-[#091223] border border-cyan-900 p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-4xl font-black text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ★★★★★
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-gray-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Avis clients
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
