"use client";

import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";

export default function Hero() {
  return (
      <section className="relative overflow-hidden bg-[#040816]">

            {/* Halo lumineux */}
                  <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(34,211,238,0.20),transparent_70%)]" />

                        <div className="relative max-w-7xl mx-auto px-6 py-24 lg:py-32">

                                <div className="grid lg:grid-cols-2 gap-16 items-center">

                                          {/* Texte */}
                                                    <motion.div
                                                                initial={{ opacity: 0, x: -60 }}
                                                                            animate={{ opacity: 1, x: 0 }}
                                                                                        transition={{ duration: 0.8 }}
                                                                                                  >

                                                                                                              <span className="inline-block rounded-full border border-cyan-500 px-4 py-2 text-cyan-400 text-sm tracking-widest uppercase">
                                                                                                                            Boutique officielle TCG
                                                                                                                                        </span>

                                                                                                                                                    <h1 className="mt-8 text-6xl lg:text-7xl font-black leading-tight">
                                                                                                                                                                  AONAMI
                                                                                                                                                                                <span className="block text-cyan-400">
                                                                                                                                                                                                TCG
                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                          </h1>

                                                                                                                                                                                                                                      <p className="mt-8 text-gray-400 text-xl leading-9 max-w-xl">
                                                                                                                                                                                                                                                    Pokémon, One Piece, Lorcana, Yu-Gi-Oh!,
                                                                                                                                                                                                                                                                  accessoires, protections, displays,
                                                                                                                                                                                                                                                                                boosters et produits officiels.
                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                        <div className="flex flex-wrap gap-5 mt-10">

                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                      href="/boutique"
                                                                                                                                                                                                                                                                                                                                                      className="flex items-center gap-2 rounded-xl bg-cyan-500 px-8 py-4 font-bold text-black hover:bg-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                    Découvrir la boutique
                                                                                                                                                                                                                                                                                                                                                                                                    <ArrowRight size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/categorie"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="rounded-xl border border-cyan-500 px-8 py-4 hover:bg-cyan-500/10 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Voir les catégories
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Logo */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, scale: 0.8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              animate={{ opacity: 1, scale: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition={{ duration: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex justify-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          src="/image/logo.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alt="AONAMI TCG"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-[520px] max-w-full drop-shadow-[0_0_80px_rgba(34,211,238,.7)]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }