"use client";

import { useState } from "react";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ProductGrid from "../components/ProductGrid";
import SearchBar from "../components/SearchBar";

export default function Boutique() {
  const [search, setSearch] = useState("");

    return (
        <>
              <Navbar />

                    <main className="min-h-screen bg-[#040816] text-white">

                            {/* Hero */}
                                    <section className="border-b border-cyan-900">

                                              <div className="max-w-7xl mx-auto px-6 py-20">

                                                          <p className="uppercase tracking-[6px] text-cyan-400">
                                                                        Boutique
                                                                                    </p>

                                                                                                <h1 className="mt-4 text-6xl font-black">
                                                                                                              Tous nos produits
                                                                                                                          </h1>

                                                                                                                                      <p className="mt-6 text-gray-400 text-lg max-w-2xl">
                                                                                                                                                    Retrouvez toutes nos cartes, boosters,
                                                                                                                                                                  displays, coffrets et accessoires officiels.
                                                                                                                                                                              </p>

                                                                                                                                                                                        </div>

                                                                                                                                                                                                </section>

                                                                                                                                                                                                        {/* Barre de recherche */}

                                                                                                                                                                                                                <SearchBar
                                                                                                                                                                                                                          value={search}
                                                                                                                                                                                                                                    onChange={setSearch}
                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                    {/* Filtres */}

                                                                                                                                                                                                                                                            <section className="max-w-7xl mx-auto px-6 py-10">

                                                                                                                                                                                                                                                                      <div className="flex flex-wrap gap-4">

                                                                                                                                                                                                                                                                                  <button className="rounded-full bg-cyan-500 px-6 py-3 font-bold text-black">
                                                                                                                                                                                                                                                                                                Tous
                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                        <button className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black transition">
                                                                                                                                                                                                                                                                                                                                      Pokémon
                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                              <button className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black transition">
                                                                                                                                                                                                                                                                                                                                                                            One Piece
                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                    <button className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black transition">
                                                                                                                                                                                                                                                                                                                                                                                                                  Lorcana
                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Accessoires
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Tri */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="max-w-7xl mx-auto px-6 pb-10">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-center">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Découvrez notre catalogue.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select className="rounded-xl border border-cyan-700 bg-[#08111f] px-5 py-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option>Popularité</option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option>Prix croissant</option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option>Prix décroissant</option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option>Nouveautés</option>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ProductGrid />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Footer />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }