"use client";

import { useState } from "react";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ProductGrid from "../components/ProductGrid";
import SearchBar from "../components/SearchBar";

export default function Boutique() {
  const [search, setSearch] = useState("");
    const [category, setCategory] = useState("all");

      return (
          <>
                <Navbar />

                      <main className="min-h-screen bg-[#040816] text-white">

                              <section className="border-b border-cyan-900">
                                        <div className="max-w-7xl mx-auto px-6 py-20">

                                                    <p className="uppercase tracking-[6px] text-cyan-400">
                                                                  Boutique
                                                                              </p>

                                                                                          <h1 className="mt-4 text-6xl font-black">
                                                                                                        Tous nos produits
                                                                                                                    </h1>

                                                                                                                                <p className="mt-6 text-gray-400 text-lg max-w-2xl">
                                                                                                                                              Retrouvez tous nos produits officiels.
                                                                                                                                                          </p>

                                                                                                                                                                    </div>
                                                                                                                                                                            </section>

                                                                                                                                                                                    <SearchBar
                                                                                                                                                                                              value={search}
                                                                                                                                                                                                        onChange={setSearch}
                                                                                                                                                                                                                />

                                                                                                                                                                                                                        <section className="max-w-7xl mx-auto px-6 py-8">

                                                                                                                                                                                                                                  <div className="flex flex-wrap gap-4">

                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                            onClick={() => setCategory("all")}
                                                                                                                                                                                                                                                                          className="rounded-full bg-cyan-500 px-6 py-3 font-bold text-black"
                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                    Tous
                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                          onClick={() => setCategory("pokemon")}
                                                                                                                                                                                                                                                                                                                                                        className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black"
                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                  Pokémon
                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setCategory("onepiece")}
                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                One Piece
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setCategory("lorcana")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Lorcana
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setCategory("accessoires")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-full border border-cyan-700 px-6 py-3 hover:bg-cyan-500 hover:text-black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Accessoires
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ProductGrid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            search={search}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      category={category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }