"use client";

import { notFound } from "next/navigation";
import { Heart, ShoppingCart } from "lucide-react";

import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { products } from "../../../data/products";
import { useCart } from "../../../contexts/CartContext";

type Props = {
  params: {
      id: string;
        };
        };

        export default function ProductPage({ params }: Props) {
          const { addToCart } = useCart();

            const product = products.find(
                (p) => p.id === Number(params.id)
                  );

                    if (!product) {
                        notFound();
                          }

                            return (
                                <>
                                      <Navbar />

                                            <main className="min-h-screen bg-[#040816] text-white">

                                                    <section className="max-w-7xl mx-auto px-6 py-20">

                                                              <div className="grid lg:grid-cols-2 gap-16">

                                                                          <div className="rounded-3xl border border-cyan-900 bg-[#08111f] p-8">

                                                                                        <img
                                                                                                        src={product.image}
                                                                                                                        alt={product.title}
                                                                                                                                        className="w-full rounded-2xl"
                                                                                                                                                      />

                                                                                                                                                                  </div>

                                                                                                                                                                              <div>

                                                                                                                                                                                            {product.badge && (
                                                                                                                                                                                                            <span className="rounded-full bg-cyan-500 px-4 py-2 font-bold text-black">
                                                                                                                                                                                                                              {product.badge}
                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                          <h1 className="mt-6 text-5xl font-black">
                                                                                                                                                                                                                                                                                          {product.title}
                                                                                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                                                                                                      <p className="mt-6 text-lg text-gray-400">
                                                                                                                                                                                                                                                                                                                                      {product.description}
                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-8 text-5xl font-black text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                  {product.price.toFixed(2)} €
                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-4 font-bold text-green-400">
                                                                                                                                                                                                                                                                                                                                                                                                                              ✔ {product.stock} en stock
                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-10 flex gap-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addToCart({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id: product.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: product.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  price: product.price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        image: product.image,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-500 py-4 font-bold text-black hover:bg-cyan-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ShoppingCart size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Ajouter au panier
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="rounded-xl border border-cyan-700 px-6 hover:bg-cyan-500 hover:text-black transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Heart size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Footer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }