"use client";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { useCart } from "../../contexts/CartContext";

export default function PanierPage() {
  const {
      cart,
          totalPrice,
              totalItems,
                  removeFromCart,
                    } = useCart();

                      return (
                          <>
                                <Navbar />

                                      <main className="min-h-screen bg-[#040816] text-white">

                                              <section className="max-w-7xl mx-auto py-16 px-6">

                                                        <h1 className="text-5xl font-black">
                                                                    Mon panier
                                                                              </h1>

                                                                                        <p className="text-gray-400 mt-3">
                                                                                                    {totalItems} article(s)
                                                                                                              </p>

                                                                                                                        <div className="mt-10 space-y-6">

                                                                                                                                    {cart.length === 0 && (

                                                                                                                                                  <div className="rounded-3xl border border-cyan-900 bg-[#08111f] p-10 text-center">

                                                                                                                                                                  <h2 className="text-3xl font-bold">
                                                                                                                                                                                    Votre panier est vide
                                                                                                                                                                                                    </h2>

                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                          {cart.map((item) => (

                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                        key={item.id}
                                                                                                                                                                                                                                                                                        className="rounded-3xl border border-cyan-900 bg-[#08111f] p-6 flex justify-between items-center"
                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                      <div className="flex gap-5 items-center">

                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                            src={item.image}
                                                                                                                                                                                                                                                                                                                                                                                className="h-28 w-28 rounded-xl object-cover"
                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                    <div>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-cyan-400 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {item.price.toFixed(2)} €
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Quantité : {item.quantity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => removeFromCart(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-xl bg-red-600 px-6 py-3 hover:bg-red-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Supprimer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-12 rounded-3xl border border-cyan-900 bg-[#08111f] p-8">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between text-3xl font-black">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Total</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {totalPrice.toFixed(2)} €
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="mt-8 w-full rounded-xl bg-cyan-500 py-4 text-xl font-bold text-black hover:bg-cyan-400">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Passer la commande

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Footer />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }